---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - eac_rails_delayed_job.gemspec
Metrics/MethodLength:
  Exclude:
  - db/migrate/20210720024221_create_delayed_jobs.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
